package io.github.francescodonnini;

import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.Node;
import com.github.javaparser.ast.body.*;
import com.github.javaparser.ast.expr.ObjectCreationExpr;
import com.github.javaparser.ast.nodeTypes.NodeWithParameters;
import io.github.francescodonnini.utils.GitUtils;
import org.eclipse.jgit.api.errors.GitAPIException;
import org.eclipse.jgit.revwalk.RevCommit;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.stream.Stream;

public class CrossCheck {

    public static void main(String[] args) throws IOException, GitAPIException {
        var rootPath = Path.of("/home/francesco/Documents/Università/ISW/60/sources/bookkeeper");
        try (var git = GitUtils.createGit(rootPath)) {
            var commits = List.of(
                    "1c90be",
                    "a2cd98",
                    "ec430a",
                    "455aab",
                    "8dafa9",
                    "0345c8",
                    "c9db76",
                    "6286c3",
                    "e47fb5",
                    "089735",
                    "88a61e"
            );
            var all = new ArrayList<String>();
            var order = 0;
            var total = 0L;
            for (var commit :  commits) {
                git.checkout()
                        .setName(commit)
                        .call();
                try (Stream<Path> paths = Files.walk(rootPath)) {
                    var count = paths
                            .filter(p -> p.toString().endsWith(".java"))
                            .filter(p -> !isGenerated(p))
                            .mapToLong(p -> countMethodsInFile(p, all))
                            .sum();
                    System.out.printf("Release %d: #methods %d%n", order, count);
                    order++;
                    total += count;
                }
            }
            Files.write(
                    Path.of("/home/francesco/Documents/Università/ISW/60/data/ck_tool_signatures.txt"),
                    all.stream()
                            .sorted()
                            .toList());
            System.out.println("Total Methods (excluding anonymous): " + total);
        }
    }

    private static boolean isGenerated(Path path) {
        try (var lines = Files.lines(path)) {
            return lines.limit(100).anyMatch(CrossCheck::hasAutogeneratedCodeHint);
        } catch (IOException e) {
            return true;
        }
    }

    private static boolean hasAutogeneratedCodeHint(String line) {
        line = line.toLowerCase();
        return line.contains("generated by the protocol buffer compiler")
                || line.contains("do not edit!")
                || line.contains("autogenerated by thrift");
    }


    private static long countMethodsInFile(Path path, List<String> all) {
        try {
            var list = new ArrayList<String>();
            // Parse the file purely as syntax
            var cu = StaticJavaParser.parse(path);
            cu.findAll(MethodDeclaration.class).stream()
                    .filter(CrossCheck::isValidMethod)
                    .forEach(m -> {
                        var className = getEnclosingClassName(m);
                        list.add(className + "::" + m.getNameAsString());
                    });
            cu.findAll(ConstructorDeclaration.class).stream()
                    .filter(CrossCheck::isValidConstructor)
                    .forEach(m -> {
                        var className = getEnclosingClassName(m);
                        list.add(className + "::" + m.getNameAsString());
                    });
            all.addAll(list);
            return list.size();
        } catch (Exception e) {
            // If a single file fails (e.g. strict syntax error), log it but DO NOT CRASH
            System.err.println("Failed to parse: " + path);
            return 0;
        }
    }

    private static String getEnclosingClassName(ConstructorDeclaration method) {
        return method.findAncestor(TypeDeclaration.class)
                .map(TypeDeclaration::getNameAsString)
                .orElse("UnknownClass"); // Should not happen for valid methods
    }

    private static String getEnclosingClassName(MethodDeclaration method) {
        return method.findAncestor(TypeDeclaration.class)
                .map(TypeDeclaration::getNameAsString)
                .orElse("UnknownClass"); // Should not happen for valid methods
    }

    private static boolean isValidMethod(MethodDeclaration node) {
        return isValid(node.getParentNode().orElse(null));
    }

    private static boolean isValidConstructor(ConstructorDeclaration node) {
        return isValid(node.getParentNode().orElse(null));
    }

    private static boolean isValid(Node parent) {
        if (parent instanceof ObjectCreationExpr) {
            return false;
        }
        if (parent instanceof TypeDeclaration) {
            if (isClassGenerated((TypeDeclaration<?>) parent)) {
                return false;
            }
        }
        return parent instanceof ClassOrInterfaceDeclaration
                || parent instanceof EnumDeclaration
                || parent instanceof AnnotationDeclaration;
    }

    private static boolean isClassGenerated(TypeDeclaration<?> node) {
        for (var annotation : node.getAnnotations()) {
            // "getName().asString()" gets the annotation name as it appears in code (e.g. "Generated")
            if (annotation.getName().asString().matches("(?i).*generated\\b")) {
                return true;
            }
        }
        return false;
    }
}