package io.github.francescodonnini.data;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.StringReader;

public class AutoGenerated {
    private AutoGenerated() {}

    public static boolean isGenerated(String content) throws IOException {
        try (var reader = new BufferedReader(new StringReader(content))) {
            return reader
                    .lines()
                    .limit(100)
                    .anyMatch(AutoGenerated::hasAutogeneratedCodeHint);
        }
    }

    private static boolean hasAutogeneratedCodeHint(String line) {
        line = line.toLowerCase();
        return line.contains("generated by the protocol buffer compiler")
                || line.contains("do not edit!")
                || line.contains("autogenerated by thrift");
    }
}
