package io.github.francescodonnini.data;

import io.github.francescodonnini.data.pmd.JavaLanguage;
import io.github.francescodonnini.data.pmd.PMDFactory;
import io.github.francescodonnini.model.RevisionJavaClass;
import net.sourceforge.pmd.PMDConfiguration;
import net.sourceforge.pmd.lang.document.FileId;
import net.sourceforge.pmd.lang.document.TextFile;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

public class JavaFileAnalyzer {
    private final Logger logger = Logger.getLogger(JavaFileAnalyzer.class.getName());
    private final Path projectPath;
    private final Path reportsPath;
    private final PMDConfiguration pmdConfig;
    private final JavaClassAnalyzerFactory factory;

    public JavaFileAnalyzer(JavaClassAnalyzerFactory factory, Path projectPath, Path reportsPath) {
        this.factory = factory;
        this.reportsPath = reportsPath;
        this.projectPath = projectPath;
        pmdConfig = PMDFactory.create();
    }

    public List<RevisionJavaClass> analyzeFile(Path file) throws IOException {
        if (!Files.exists(file)) {
            throw new IOException("File '" + file + "' not found");
        }

        var reportPath = reportsPath.resolve(file.getFileName());
        try (var pmd = PMDFactory.create(reportPath, pmdConfig)) {

            var content = Files.readString(file, StandardCharsets.UTF_8);
            if (AutoGenerated.isGenerated(content)) {
                logger.log(Level.INFO, "File {0} is auto-generated", file);
                return List.of();
            }

            var textFile = TextFile
                    .builderForCharSeq(content, FileId.fromPath(file), JavaLanguage.LANGUAGE_VERSION)
                    .build();
            pmd.files().addFile(textFile);

            var ctx = new ParseContext(
                    0L,
                    "local",
                    projectPath,
                    file,
                    LocalDateTime.now(),
                    content
            );
            var parsedClasses = parseClass(ctx);

            pmd.performAnalysis();
            logger.log(Level.INFO, "Successfully analyzed local file {0}", file);

            return parsedClasses;
        }
    }

    private List<RevisionJavaClass> parseClass(ParseContext ctx) {
        try {
            var extractor = factory.create();
            return extractor.run(ctx.getAbsolutePath(), ctx.content());
        } catch (IOException e) {
            logger.log(Level.SEVERE, e, () -> "Error parsing file " + ctx.path());
            return List.of();
        }
    }
}
