package io.github.francescodonnini.data;

import io.github.francescodonnini.collectors.ast.*;
import io.github.francescodonnini.data.pmd.CPDConsumer;
import io.github.francescodonnini.data.pmd.CPDFactory;
import io.github.francescodonnini.data.pmd.JavaLanguage;
import io.github.francescodonnini.data.pmd.PMDFactory;
import io.github.francescodonnini.model.JavaClass;
import net.sourceforge.pmd.PMDConfiguration;
import net.sourceforge.pmd.cpd.CPDConfiguration;
import net.sourceforge.pmd.cpd.CpdAnalysis;
import net.sourceforge.pmd.lang.document.FileId;
import net.sourceforge.pmd.lang.document.TextFile;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

public class JavaFileAnalyzer {
    private final Logger logger = Logger.getLogger(JavaFileAnalyzer.class.getName());
    private final Path projectPath;
    private final Path reportsPath;
    private final PMDConfiguration pmdConfig;
    private final CPDConfiguration cpdConfig;
    private final AbstractCounterFactory factory;

    public JavaFileAnalyzer(AbstractCounterFactory factory, Path projectPath, Path reportsPath) {
        this.factory = factory;
        this.reportsPath = reportsPath;
        this.projectPath = projectPath;
        pmdConfig = PMDFactory.create();
        cpdConfig = CPDFactory.create();
    }

    public List<JavaClass> analyzeFile(Path file) throws IOException {
        if (!Files.exists(file)) {
            throw new IOException("File '" + file + "' not found");
        }

        var reportPath = reportsPath.resolve(file.getFileName());
        try (var pmd = PMDFactory.create(reportPath, pmdConfig);
             var cpd = CpdAnalysis.create(cpdConfig)) {

            var content = Files.readString(file, StandardCharsets.UTF_8);
            if (AutoGenerated.isGenerated(content)) {
                logger.log(Level.INFO, "File {0} is auto-generated", file);
                return List.of();
            }

            var textFile = TextFile
                    .builderForCharSeq(content, FileId.fromPath(file), JavaLanguage.LANGUAGE_VERSION)
                    .build();
            pmd.files().addFile(textFile);
            cpd.files().addFile(textFile);

            var ctx = new ParseContext(
                    0L,
                    "local",
                    projectPath,
                    file,
                    LocalDateTime.now(),
                    content
            );
            var parsedClasses = parseClass(ctx);

            pmd.performAnalysis();
            cpd.performAnalysis(new CPDConsumer(parsedClasses));
            logger.log(Level.INFO, "Successfully analyzed local file {0}", file);

            return parsedClasses;
        }
    }

    private List<JavaClass> parseClass(ParseContext ctx) {
        try {
            var extractor = new JavaMethodExtractor(createCounters(factory));
            extractor.parse(ctx);
            return extractor.getClasses();
        } catch (IOException e) {
            logger.log(Level.SEVERE, e, () -> "Error parsing file " + ctx.path());
            return List.of();
        }
    }

    private List<AbstractCounter> createCounters(AbstractCounterFactory factory) {
        return List.of(
                factory.build(CyclomaticComplexityCounter.class),
                factory.build(InputParametersCounter.class),
                factory.build(StatementsCounter.class),
                factory.build(ElseCounter.class),
                factory.build(NestingDepth.class),
                factory.build(HalsteadComplexityCounter.class));
    }
}
